# Generated by Django 5.2.9 on 2026-09-22 12:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('x', 'X / Twitter'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('threads', 'Threads'), ('reddit', 'Reddit'), ('email', 'Email'), ('referral', 'Referral'), ('other', 'Other')], default='linkedin', help_text='Where you found them', max_length=20)),
                ('social_handle', models.CharField(blank=True, help_text='Their @username on that platform', max_length=150)),
                ('profile_url', models.URLField(blank=True, help_text='Link to their profile')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('replied', 'Replied'), ('in_conversation', 'In conversation'), ('converted', 'Converted'), ('dead', 'Dead / No interest')], default='new', max_length=20)),
                ('business', models.CharField(blank=True, choices=[('djangify', 'Djangify'), ('inspirational_guidance', 'Inspirational Guidance'), ('self_talk_effect', 'The Self-Talk Effect'), ('todiane', 'todiane.com'), ('other', 'Other')], help_text='Which business this contact relates to', max_length=30)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated, e.g. coach, warm lead', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, help_text='When to follow up next', null=True)),
                ('follow_up_1_done', models.BooleanField(default=False, verbose_name='Follow-up 1 done')),
                ('follow_up_2_done', models.BooleanField(default=False, verbose_name='Follow-up 2 done')),
                ('follow_up_3_done', models.BooleanField(default=False, verbose_name='Follow-up 3 done')),
                ('joined_email_list', models.BooleanField(default=False, help_text='Signed up for the email list', verbose_name='Joined email list')),
                ('made_purchase', models.BooleanField(default=False, help_text='This contact has bought something')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount this contact has paid', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveSmallIntegerField(choices=[(1, 'Follow-up 1'), (2, 'Follow-up 2'), (3, 'Follow-up 3')], unique=True)),
                ('message', models.TextField(help_text='Reusable message for this follow-up stage')),
            ],
            options={
                'ordering': ['stage'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('channel', models.CharField(choices=[('dm', 'Direct message'), ('comment', 'Comment'), ('email', 'Email'), ('call', 'Call'), ('meeting', 'Meeting'), ('other', 'Other')], default='dm', max_length=20)),
                ('direction', models.CharField(choices=[('outbound', 'I reached out'), ('inbound', 'They reached out')], default='outbound', max_length=20)),
                ('message', models.TextField(help_text='What was said')),
                ('image', models.ImageField(blank=True, help_text='Optional screenshot (e.g. of a comment or DM)', null=True, upload_to='crm/interactions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.contact')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
