# Generated by Django 5.2.18 on 2026-10-09 17:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('x', 'X / Twitter'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('threads', 'Threads'), ('reddit', 'Reddit'), ('email', 'Email'), ('referral', 'Referral'), ('other', 'Other')], default='linkedin', help_text='Where you found them', max_length=20)),
                ('social_handle', models.CharField(blank=True, help_text='Their @username on that platform', max_length=150)),
                ('profile_url', models.URLField(blank=True, help_text='Link to their profile')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('replied', 'Replied'), ('in_conversation', 'In conversation'), ('converted', 'Converted'), ('dead', 'Dead / No interest')], default='new', max_length=20)),
                ('business', models.CharField(blank=True, help_text='Which of your businesses or projects this contact relates to', max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated, e.g. coach, warm lead', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, help_text='When to follow up next', null=True)),
                ('follow_up_1_done', models.BooleanField(default=False, verbose_name='Follow-up 1 done')),
                ('follow_up_2_done', models.BooleanField(default=False, verbose_name='Follow-up 2 done')),
                ('follow_up_3_done', models.BooleanField(default=False, verbose_name='Follow-up 3 done')),
                ('joined_email_list', models.BooleanField(default=False, help_text='Signed up for the email list', verbose_name='Joined email list')),
                ('made_purchase', models.BooleanField(default=False, help_text='This contact has bought something')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount this contact has paid', max_digits=10, null=True)),
                ('next_touch_date', models.DateField(blank=True, help_text="Post-sale check-in reminder (thank-you, how's it going, re-offer)", null=True)),
                ('next_touch_note', models.CharField(blank=True, help_text='What the next check-in is for', max_length=255)),
                ('dead_reason', models.CharField(blank=True, help_text='Why this went dead (required when status is Dead)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveSmallIntegerField(choices=[(1, 'Follow-up 1'), (2, 'Follow-up 2'), (3, 'Follow-up 3')], unique=True)),
                ('message', models.TextField(help_text='Reusable message for this follow-up stage')),
            ],
            options={
                'ordering': ['stage'],
            },
        ),
        migrations.CreateModel(
            name='SearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(help_text='Which of your businesses or projects this profile searches for', max_length=100, unique=True)),
                ('website', models.URLField(blank=True)),
                ('audience_description', models.TextField(blank=True, help_text='Who the ideal prospect is, in plain words')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated signal phrases, e.g. freelance designer, sick of spreadsheets, alternative to <competitor>')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['business'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('contact_created', 'Contact created'), ('status_changed', 'Status changed'), ('stage_completed', 'Follow-up stage updated'), ('check_in_done', 'Check-in done'), ('purchase_logged', 'Purchase logged')], max_length=30)),
                ('content', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.contact')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('channel', models.CharField(choices=[('dm', 'Direct message'), ('comment', 'Comment'), ('email', 'Email'), ('call', 'Call'), ('meeting', 'Meeting'), ('other', 'Other')], default='dm', max_length=20)),
                ('direction', models.CharField(choices=[('outbound', 'I reached out'), ('inbound', 'They reached out')], default='outbound', max_length=20)),
                ('message', models.TextField(help_text='What was said')),
                ('image', models.ImageField(blank=True, help_text='Optional screenshot (e.g. of a comment or DM)', null=True, upload_to='crm/interactions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.contact')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('import', 'Imported')], default='manual', max_length=20)),
                ('external_order_id', models.CharField(blank=True, help_text='Order id from the system it was imported from, used to avoid importing the same order twice', max_length=100, null=True, unique=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='crm.contact')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
