# Generated by Django 5.2.9 on 2026-09-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(choices=[('djangify', 'Djangify'), ('inspirational_guidance', 'Inspirational Guidance'), ('self_talk_effect', 'The Self-Talk Effect'), ('todiane', 'todiane.com'), ('other', 'Other')], help_text='Which business this profile searches for', max_length=30, unique=True)),
                ('website', models.URLField(blank=True)),
                ('audience_description', models.TextField(blank=True, help_text='Who the ideal prospect is, in plain words')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated signal phrases, e.g. life coach, Gumroad, sick of paying fees, alternative to Kajabi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['business'],
            },
        ),
    ]
