# Generated by Django 5.2.9 on 2026-09-24 19:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_searchprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='next_touch_date',
            field=models.DateField(blank=True, help_text="Post-sale check-in reminder (thank-you, how's it going, re-offer)", null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='next_touch_note',
            field=models.CharField(blank=True, help_text='What the next check-in is for', max_length=255),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('djangify', 'Djangify sync')], default='manual', max_length=20)),
                ('external_order_id', models.CharField(blank=True, help_text='Djangify order id, used to avoid importing the same order twice', max_length=100, null=True, unique=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='crm.contact')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
