# Generated by Django 5.2.9 on 2026-09-24 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_contact_next_touch_date_contact_next_touch_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='dead_reason',
            field=models.CharField(blank=True, help_text='Why this went dead (required when status is Dead)', max_length=255),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('contact_created', 'Contact created'), ('status_changed', 'Status changed'), ('stage_completed', 'Follow-up stage updated'), ('check_in_done', 'Check-in done'), ('purchase_logged', 'Purchase logged')], max_length=30)),
                ('content', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.contact')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
