# Generated by Django 5.2.9 on 2026-10-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_contact_dead_reason_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='business',
            field=models.CharField(blank=True, help_text='Which of your businesses or projects this contact relates to', max_length=100),
        ),
        migrations.AlterField(
            model_name='searchprofile',
            name='business',
            field=models.CharField(help_text='Which of your businesses or projects this profile searches for', max_length=100, unique=True),
        ),
    ]
