# Generated by Django 5.2.9 on 2026-09-23 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(choices=[('djangify', 'Djangify'), ('inspirational_guidance', 'Inspirational Guidance'), ('self_talk_effect', 'The Self-Talk Effect'), ('todiane', 'todiane.com'), ('other', 'Other')], help_text='Which of our businesses this competitor overlaps with', max_length=30)),
                ('platform', models.CharField(choices=[('meta', 'Meta (Facebook/Instagram)'), ('google', 'Google'), ('linkedin', 'LinkedIn'), ('other', 'Other')], default='meta', max_length=20)),
                ('competitor_name', models.CharField(max_length=150)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('angle', models.TextField(help_text='The messaging angle/positioning this ad uses')),
                ('ad_copy', models.TextField(blank=True, help_text='Full ad copy, if captured')),
                ('link', models.URLField(blank=True, help_text='Link to the ad or a screenshot')),
                ('date_pulled', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_pulled', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(choices=[('djangify', 'Djangify'), ('inspirational_guidance', 'Inspirational Guidance'), ('self_talk_effect', 'The Self-Talk Effect'), ('todiane', 'todiane.com'), ('other', 'Other')], help_text='Which of our businesses this keyword research is for', max_length=30)),
                ('term', models.CharField(max_length=255)),
                ('difficulty_score', models.PositiveIntegerField(blank=True, help_text='Keyword difficulty, 0-100', null=True)),
                ('search_volume', models.PositiveIntegerField(blank=True, null=True)),
                ('top_ranking_domain', models.CharField(blank=True, help_text='Who currently ranks for this term', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['business', 'term'],
                'constraints': [models.UniqueConstraint(fields=('business', 'term'), name='unique_keyword_per_business')],
            },
        ),
        migrations.CreateModel(
            name='PainTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(choices=[('djangify', 'Djangify'), ('inspirational_guidance', 'Inspirational Guidance'), ('self_talk_effect', 'The Self-Talk Effect'), ('todiane', 'todiane.com'), ('other', 'Other')], help_text='Which of our businesses this pain theme is relevant to', max_length=30)),
                ('theme', models.CharField(help_text='Short label for the theme', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Synthesized summary of the theme')),
                ('quote_count', models.PositiveIntegerField(default=0, help_text='How many supporting quotes were found')),
                ('source_breakdown', models.CharField(blank=True, help_text="e.g. 'Reddit: 5, Trustpilot: 3, G2: 2'", max_length=255)),
                ('example_quotes', models.TextField(blank=True, help_text='Representative quotes, with source links')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['business', '-quote_count'],
                'constraints': [models.UniqueConstraint(fields=('business', 'theme'), name='unique_pain_theme_per_business')],
            },
        ),
    ]
