# Generated by Django 5.2.9 on 2026-10-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorad',
            name='business',
            field=models.CharField(help_text='Which of your businesses or projects this competitor overlaps with', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='business',
            field=models.CharField(help_text='Which of your businesses or projects this keyword research is for', max_length=100),
        ),
        migrations.AlterField(
            model_name='paintheme',
            name='business',
            field=models.CharField(help_text='Which of your businesses or projects this pain theme is relevant to', max_length=100),
        ),
    ]
